### ISSUE TITLE
Unable to define class without all params

### ISSUE THREAD

**Issue by gregmark** [ucbpi/puppet-vnc#1]
So if I define it like this:

``` puppet
$vnc_user = {
  'user' => $::hostname,
  'args' => '-geometry 1024x768 -depth 16'
}

class { 'vnc':
    refresh => true,
    servers => [ $vnc_user ],
    service_enable => true,
    service_ensure => running,
    xstartup_template => 'vnc/xstartup.erb',
    vncservers_template => 'vnc/vncservers.erb',
}
```

It works fine, but if I remove any of the params to take advantage of the defaults like this:

``` puppet
class { 'vnc':
     servers => [ $vnc_user ],
    service_enable => true,
    service_ensure => running,
}
```

Runs of the agent on the clients error out with this:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Puppet::Parser::AST::Resource failed with error NoMethodError: undefined method `[]' for nil:NilClass at /etc/puppet/modules/site/manifests/init.pp:69 on node yzhou.cloud.streamsage.com

User conner on #puppet suggested that https://github.com/arusso/puppet-vnc/blob/master/templates/vncservers.erb lacked a test for $user or $args.

Thanks.

**Comment by arusso** [comment]
Is `$vnc_user` still defined in the second example, or is that removed too?

**Comment by arusso** [comment]
This should have been addressed when I added a validation check `validate_vnc_servers` in version `0.0.3`.
